server:
  port: 8761
eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: eurekahost.poolcar.com
    lease-renewal-interval-in-seconds: 30
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF